
// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unit-tested
// in isolation, and perhaps even published as a re-useable package.
//
// However, the details of how this helper code works (e.g. the way that
// different builtin types are passed across the FFI) must exactly match
// what's expected by the Rust code on the other side of the interface. In
// practice that means coming from the exact version of `uniffi` that was
// used to compile the Rust component. The easiest way to ensure this is to
// bundle the Kotlin helpers directly inline like we're doing here.

{% include "RustBufferTemplate.kt" %}
{% include "FfiConverterTemplate.kt" %}
{% include "Helpers.kt" %}

{%- if ci.contains_object_types() %}
{#- UniffiCleaner + NoHandle / UniffiWithHandle markers. Only needed
    when the interface exposes at least one object type. Gating here
    mirrors `NamespaceLibraryTemplate.java`'s `contains_object_types()`
    check; cuts ~135 lines of runtime out of fixtures that don't need
    it. -#}
{% include "UniffiCleaner.kt" %}
{%- endif %}

{%- if ci.has_callback_definitions() || ci.has_async_fns() %}
{#- UniffiHandleMap (odd-handle ConcurrentHashMap) is needed by both
    the callback-interface runtime AND the async runtime — Async.kt
    keys its continuation handle map on `UniffiHandleMap`. Emit
    once when either feature is in use. -#}
{% include "HandleMap.kt" %}
{%- endif %}
{%- if ci.has_callback_definitions() %}
{#- Callback-interface runtime: FfiConverterCallbackInterface
    (abstract base class that routes lift/lower through the handle
    map). Only emitted when the interface has at least one callback
    interface or `[Trait, WithForeign]` object; parallel to the
    Java backend's `include_once_check("CallbackInterfaceRuntime.java")`
    dance. -#}
{% include "CallbackInterfaceRuntime.kt" %}
{%- endif %}

// Contains loading, initialization code, and the FFI Function declarations
// using Java FFM (Foreign Function & Memory API).
{% include "NamespaceLibraryTemplate.kt" %}

{#- Async support — only emitted when the interface declares any
    `async fn` (free function or method). Generated `suspend fun`
    signatures route through `UniffiAsyncHelpers.uniffiRustCallAsync`,
    which uses `kotlinx.coroutines.suspendCancellableCoroutine` for
    the polling continuation. Consumers must have
    `org.jetbrains.kotlinx:kotlinx-coroutines-core` on classpath. -#}
{%- if ci.has_async_fns() %}
{% include "Async.kt" %}
{%- endif %}

// Primitive + String + ByteArray FfiConverters. All are emitted
// unconditionally for now; a later revision will gate them on which types
// the interface actually uses (mirroring the Java `Types.java` dispatch
// logic, which needs Askama filter machinery on the Kotlin side that
// doesn't exist yet).
{% include "Int8Helper.kt" %}
{% include "Int16Helper.kt" %}
{% include "Int32Helper.kt" %}
{% include "Int64Helper.kt" %}
{% include "Float32Helper.kt" %}
{% include "Float64Helper.kt" %}
{% include "BooleanHelper.kt" %}
{% include "StringHelper.kt" %}
{% include "ByteArrayHelper.kt" %}
{% include "Int16ArrayHelper.kt" %}
{% include "Int32ArrayHelper.kt" %}
{% include "Int64ArrayHelper.kt" %}
{% include "Float32ArrayHelper.kt" %}
{% include "Float64ArrayHelper.kt" %}
{% include "BooleanArrayHelper.kt" %}

{# Per-type templates. Iterates `iter_local_types()` and includes the
   matching template for each Type variant, mirroring the Java backend's
   `Types.java` dispatch. Handled in P3f/P3g: records, Optional<T>, flat
   enums, typed errors. Non-flat enums and other types (sequences, maps,
   objects, callbacks, ...) still panic at the `AsCodeType for Type` arm
   in `gen_kotlin/mod.rs`. Whitespace control trims both sides of every
   loop / match tag so non-matching types (the common case for
   primitive-only fixtures like arithmetic) emit nothing. #}
{%- for type_ in ci.iter_local_types() -%}
{%- match type_ -%}
{%- when Type::Record { name, module_path } -%}
{%- let type_name = type_|type_name(ci, config) -%}
{%- let ffi_converter_name = type_|ffi_converter_name -%}
{% include "RecordTemplate.kt" %}
{%- when Type::Enum { name, module_path } -%}
{%- let type_name = type_|type_name(ci, config) -%}
{%- let ffi_converter_name = type_|ffi_converter_name -%}
{%- if ci.is_name_used_as_error(name) -%}
{% include "ErrorTemplate.kt" %}
{%- else -%}
{% include "EnumTemplate.kt" %}
{%- endif -%}
{%- when Type::Optional { inner_type } -%}
{%- let ffi_converter_name = type_|ffi_converter_name -%}
{% include "OptionalTemplate.kt" %}
{%- when Type::Sequence { inner_type } -%}
{#- Primitive-typed sequences (Vec<i16/i32/i64/f32/f64/bool> and
   unsigned variants) have a dedicated unboxed-array FfiConverter
   shipped unconditionally via `<Type>ArrayHelper.kt`. Skipping the
   generic SequenceTemplate here avoids emitting a colliding
   `FfiConverter<Name>Array.kt` with the boxed `List<T>` body. -#}
{%- if type_|is_primitive_array_sequence -%}
{%- else -%}
{%- let ffi_converter_name = type_|ffi_converter_name -%}
{% include "SequenceTemplate.kt" %}
{%- endif -%}
{%- when Type::Map { key_type, value_type } -%}
{%- let ffi_converter_name = type_|ffi_converter_name -%}
{% include "MapTemplate.kt" %}
{%- when Type::Object { name, module_path, imp } -%}
{%- let type_name = type_|type_name(ci, config) -%}
{%- let ffi_converter_name = type_|ffi_converter_name -%}
{% include "ObjectTemplate.kt" %}
{%- when Type::CallbackInterface { name, module_path } -%}
{%- let type_name = type_|type_name(ci, config) -%}
{%- let ffi_converter_name = type_|ffi_converter_name -%}
{% include "CallbackInterfaceTemplate.kt" %}
{%- when Type::Custom { name, module_path, builtin } -%}
{%- let type_name = type_|type_name(ci, config) -%}
{%- let ffi_converter_name = type_|ffi_converter_name -%}
{% include "CustomTypeTemplate.kt" %}
{%- when Type::Timestamp -%}
{% include "TimestampHelper.kt" %}
{%- when Type::Duration -%}
{% include "DurationHelper.kt" %}
{%- else -%}
{%- endmatch -%}
{%- endfor -%}

{# Only emit the namespace object when the interface has at least one
   top-level function. Empty `object Foo` is legal Kotlin but pointless. #}
{%- if !ci.function_definitions().is_empty() %}
// UNIFFI:FILE {{ self.namespace_class_name() }}.kt
package {{ config.package_name() }}

object {{ self.namespace_class_name() }} {
    {%- for func in ci.function_definitions() %}

{% call kotlin::func_decl(func, "    ") %}
    {%- endfor %}
}
{%- endif %}

{%- import "macros.kt" as kotlin %}
