
// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unit-tested
// in isolation, and perhaps even published as a re-useable package.
//
// However, the details of how this helper code works (e.g. the way that
// different builtin types are passed across the FFI) must exactly match
// what's expected by the Rust code on the other side of the interface. In
// practice that means coming from the exact version of `uniffi` that was
// used to compile the Rust component. The easiest way to ensure this is to
// bundle the Kotlin helpers directly inline like we're doing here.

{% include "RustBufferTemplate.kt" %}
{% include "FfiConverterTemplate.kt" %}
{% include "Helpers.kt" %}

// Contains loading, initialization code, and the FFI Function declarations
// using Java FFM (Foreign Function & Memory API).
{% include "NamespaceLibraryTemplate.kt" %}

// UNIFFI:FILE {{ self.namespace_class_name() }}.kt
package {{ config.package_name() }}

// Skeleton namespace object. Real type mapping and callable functions
// will be added as the Kotlin backend matures.
object {{ self.namespace_class_name() }}
