
// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unit-tested
// in isolation, and perhaps even published as a re-useable package.
//
// However, the details of how this helper code works (e.g. the way that
// different builtin types are passed across the FFI) must exactly match
// what's expected by the Rust code on the other side of the interface. In
// practice that means coming from the exact version of `uniffi` that was
// used to compile the Rust component. The easiest way to ensure this is to
// bundle the Kotlin helpers directly inline like we're doing here.

{% include "RustBufferTemplate.kt" %}
{% include "FfiConverterTemplate.kt" %}
{% include "Helpers.kt" %}

// Contains loading, initialization code, and the FFI Function declarations
// using Java FFM (Foreign Function & Memory API).
{% include "NamespaceLibraryTemplate.kt" %}

// Primitive + String + ByteArray FfiConverters. All are emitted
// unconditionally for now; a later revision will gate them on which types
// the interface actually uses (mirroring the Java `Types.java` dispatch
// logic, which needs Askama filter machinery on the Kotlin side that
// doesn't exist yet).
{% include "Int8Helper.kt" %}
{% include "Int16Helper.kt" %}
{% include "Int32Helper.kt" %}
{% include "Int64Helper.kt" %}
{% include "Float32Helper.kt" %}
{% include "Float64Helper.kt" %}
{% include "BooleanHelper.kt" %}
{% include "StringHelper.kt" %}
{% include "ByteArrayHelper.kt" %}

{# Only emit the namespace object when the interface has at least one
   top-level function. Empty `object Foo` is legal Kotlin but pointless. #}
{%- if !ci.function_definitions().is_empty() %}
// UNIFFI:FILE {{ self.namespace_class_name() }}.kt
package {{ config.package_name() }}

object {{ self.namespace_class_name() }} {
    {%- for func in ci.function_definitions() %}

{% call kotlin::func_decl(func, "    ") %}
    {%- endfor %}
}
{%- endif %}

{%- import "macros.kt" as kotlin %}
